# Generated by Django 3.1.7 on 2021-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190820_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='describe',
            field=models.TextField(default='Chethan Django '),
        ),
    ]
