# Generated by Django 3.1.4 on 2021-04-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book1',
        ),
    ]
