# Generated by Django 3.1.4 on 2021-04-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210416_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book1',
            new_name='Book',
        ),
    ]
